---
defaults:
- scope:
    path: ''
    type: 'pages'
  values:
    encoding: 'urf-8'
    layout: 'page'
    title: 'Sleeping King Studios'
exclude:
  - .git
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - /vendor
github: false
repository: sleepingkingstudios/sleepingkingstudios.github.io
