---
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - assets/javascripts/src
defaults:
- scope:
    path: ''
    type: 'pages'
  values:
    encoding: 'urf-8'
    layout: 'page'
    title: 'Sleeping King Studios'
